development:
  adapter: postgresql
  username: "postgres"  
  password: "cosmyn12"
  host: "localhost"
  database: aplicatie_reteta
  pool: 5
test:
  adapter: postgresql
  username: "postgres"
  password: "cosmyn12"
  host: "localhost"
  database: aplicatie_reteta
  pool: 5