# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 40e96e193a3a64190523b90fe390c68340116a4a072a81e27c4a7f3b728801471fdbcc366fb7ee567a575a68d7f36bb00ca4cbdd5922020a3a4791e07fcd425d

test:
  secret_key_base: 39f45cd68406f16345ff5462670fbb5b8164ae4a69b83d098968850e479721b9e77cbf256d44703d23071030e97be319a799200d6fd2b3bb5c63b8fbd993383a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
